export interface VariantDef {
  key: string; // exact key in Index, e.g. "v-button-2"
  label: string; // heading from MDX, e.g. "Variants"
}

export interface ComponentDef {
  name: string;
  href: string;
  variants: VariantDef[];
}

export interface CategoryDef {
  label: string;
  components: ComponentDef[];
}

export const catalogue: CategoryDef[] = [
  {
    components: [
      {
        href: "/ui/actions/button",
        name: "Button",
        variants: [
          { key: "v-button-1", label: "Default" },
          { key: "v-button-2", label: "Outline" },
          { key: "v-button-3", label: "Secondary" },
          { key: "v-button-4", label: "Destructive" },
          { key: "v-button-5", label: "Destructive Outline" },
          { key: "v-button-6", label: "Ghost" },
          { key: "v-button-7", label: "Link" },
          { key: "v-button-8", label: "Extra-small Size" },
          { key: "v-button-9", label: "Small Size" },
          { key: "v-button-10", label: "Large Size" },
          { key: "v-button-11", label: "Extra-large Size" },
          { key: "v-button-12", label: "Disabled" },
          { key: "v-button-13", label: "Icon" },
          { key: "v-button-14", label: "Icon Right" },
          { key: "v-button-15", label: "Icon Left" },
          { key: "v-button-16", label: "Outline with Icon" },
          { key: "v-button-17", label: "Ghost with Icon" },
          { key: "v-button-18", label: "Destructive with Icon" },
          { key: "v-button-19", label: "Link with Icon" },
          { key: "v-button-20", label: "Star with Count" },
          { key: "v-button-21", label: "With Badge" },
          { key: "v-button-22", label: "With Shortcut" },
          { key: "v-button-23", label: "Copy Button" },
          { key: "v-button-24", label: "Hamburger Toggle" },
          { key: "v-button-25", label: "Sliding Icon" },
        ],
      },
      {
        href: "/ui/actions/switch",
        name: "Switch",
        variants: [
          { key: "v-switch-1", label: "Default" },
          { key: "v-switch-2", label: "With Description" },
          { key: "v-switch-3", label: "Sizes" },
          { key: "v-switch-4", label: "Group" },
          { key: "v-switch-5", label: "List with Icons" },
          { key: "v-switch-6", label: "Destructive" },
          { key: "v-switch-7", label: "Settings Table" },
          { key: "v-switch-8", label: "Card Grid" },
          { key: "v-switch-9", label: "Cookie Preferences" },
          { key: "v-switch-10", label: "Notification Channels" },
        ],
      },
      {
        href: "/ui/actions/toggle",
        name: "Toggle",
        variants: [
          { key: "v-toggle-1", label: "Default" },
          { key: "v-toggle-2", label: "Outline Variant" },
          { key: "v-toggle-3", label: "Sizes" },
          { key: "v-toggle-4", label: "With Button & Icon" },
          { key: "v-toggle-5", label: "With Icon" },
          { key: "v-toggle-6", label: "With Badge" },
          { key: "v-toggle-7", label: "Icon Swap" },
          { key: "v-toggle-8", label: "Label Change" },
          { key: "v-toggle-9", label: "Video Call Controls" },
          { key: "v-toggle-10", label: "Role Filter Chips" },
        ],
      },
      {
        href: "/ui/actions/toggle-group",
        name: "Toggle Group",
        variants: [
          { key: "v-toggle-group-1", label: "Default" },
          { key: "v-toggle-group-2", label: "Sizes" },
          { key: "v-toggle-group-3", label: "Outline" },
          { key: "v-toggle-group-4", label: "Vertical" },
          { key: "v-toggle-group-5", label: "Multiple Selection" },
          { key: "v-toggle-group-6", label: "Text Alignment" },
          { key: "v-toggle-group-7", label: "View Mode" },
          { key: "v-toggle-group-8", label: "Color Theme" },
          { key: "v-toggle-group-9", label: "Pricing Tier" },
          { key: "v-toggle-group-10", label: "Variant 10" },
        ],
      },
      {
        href: "/ui/actions/toolbar",
        name: "Toolbar",
        variants: [
          { key: "v-toolbar-1", label: "Default" },
          { key: "v-toolbar-2", label: "Variant 2" },
          { key: "v-toolbar-3", label: "Variant 3" },
          { key: "v-toolbar-4", label: "Variant 4" },
          { key: "v-toolbar-5", label: "Variant 5" },
          { key: "v-toolbar-6", label: "Variant 6" },
          { key: "v-toolbar-7", label: "Variant 7" },
          { key: "v-toolbar-8", label: "Variant 8" },
          { key: "v-toolbar-9", label: "Variant 9" },
          { key: "v-toolbar-10", label: "Variant 10" },
        ],
      },
    ],
    label: "Actions",
  },
  {
    components: [
      {
        href: "/ui/data/accordion",
        name: "Accordion",
        variants: [
          { key: "v-accordion-1", label: "Default" },
          { key: "v-accordion-2", label: "Single" },
          { key: "v-accordion-3", label: "Multiple" },
          { key: "v-accordion-4", label: "Controlled" },
          { key: "v-accordion-5", label: "Plus/Minus Icons" },
          { key: "v-accordion-6", label: "With Borders" },
          { key: "v-accordion-7", label: "Within a Card" },
          { key: "v-accordion-8", label: "Nested with Borders" },
          { key: "v-accordion-9", label: "User List with Avatars" },
          { key: "v-accordion-10", label: "Changelog" },
        ],
      },
      {
        href: "/ui/data/chart",
        name: "Chart",
        variants: [
          { key: "v-chart-1", label: "Default" },
          { key: "v-chart-2", label: "Variant 2" },
          { key: "v-chart-3", label: "Variant 3" },
          { key: "v-chart-4", label: "Variant 4" },
          { key: "v-chart-5", label: "Variant 5" },
          { key: "v-chart-6", label: "Variant 6" },
          { key: "v-chart-7", label: "Variant 7" },
          { key: "v-chart-8", label: "Variant 8" },
          { key: "v-chart-9", label: "Variant 9" },
          { key: "v-chart-10", label: "Variant 10" },
        ],
      },
      {
        href: "/ui/data/collapsible",
        name: "Collapsible",
        variants: [
          { key: "v-collapsible-1", label: "Default" },
          { key: "v-collapsible-2", label: "Collapsible" },
          { key: "v-collapsible-3", label: "Animated Card" },
          { key: "v-collapsible-4", label: "Bottom Trigger" },
          { key: "v-collapsible-5", label: "Form Fields" },
          { key: "v-collapsible-6", label: "Multi-level Menu" },
          { key: "v-collapsible-7", label: "Tree with Actions" },
          { key: "v-collapsible-8", label: "Read More" },
          { key: "v-collapsible-9", label: "Build Log" },
          { key: "v-collapsible-10", label: "Incident Timeline" },
        ],
      },
      {
        href: "/ui/data/empty",
        name: "Empty",
        variants: [
          { key: "v-empty-1", label: "Default" },
          { key: "v-empty-2", label: "Search Empty State" },
          { key: "v-empty-3", label: "With Search Input" },
          { key: "v-empty-4", label: "With Add Button" },
          { key: "v-empty-5", label: "Dashed Upload" },
          { key: "v-empty-6", label: "No Automations" },
          { key: "v-empty-7", label: "No Products" },
          { key: "v-empty-8", label: "No Payments" },
          { key: "v-empty-9", label: "No Events" },
          { key: "v-empty-10", label: "Variant 10" },
        ],
      },
      {
        href: "/ui/data/table",
        name: "Table",
        variants: [
          { key: "v-table-1", label: "Default" },
          { key: "v-table-2", label: "Card Style" },
          { key: "v-table-3", label: "In CardFrame" },
          { key: "v-table-4", label: "In Frame" },
          { key: "v-table-5", label: "Orders" },
          { key: "v-table-6", label: "Team Members" },
          { key: "v-table-7", label: "Subscriptions" },
          { key: "v-table-8", label: "Sortable API Endpoints" },
          { key: "v-table-9", label: "Storage Usage" },
          { key: "v-table-10", label: "Audit Log" },
        ],
      },
    ],
    label: "Data Display",
  },
  {
    components: [
      {
        href: "/ui/feedback/alert",
        name: "Alert",
        variants: [
          { key: "v-alert-1", label: "Default" },
          { key: "v-alert-2", label: "With Icon" },
          { key: "v-alert-3", label: "With Icon & Actions" },
          { key: "v-alert-4", label: "Info" },
          { key: "v-alert-5", label: "Success" },
          { key: "v-alert-6", label: "Warning" },
          { key: "v-alert-7", label: "Error" },
          { key: "v-alert-8", label: "Stacked in Frame" },
          { key: "v-alert-9", label: "With Actions in Frame" },
          { key: "v-alert-10", label: "Feature Discovery" },
        ],
      },
      {
        href: "/ui/feedback/badge",
        name: "Badge",
        variants: [
          { key: "v-badge-1", label: "Default" },
          { key: "v-badge-2", label: "Outline" },
          { key: "v-badge-3", label: "Secondary" },
          { key: "v-badge-4", label: "Destructive" },
          { key: "v-badge-5", label: "Info" },
          { key: "v-badge-6", label: "Success" },
          { key: "v-badge-7", label: "Warning" },
          { key: "v-badge-8", label: "Error" },
          { key: "v-badge-9", label: "Size Variations" },
          { key: "v-badge-10", label: "With Icon" },
          { key: "v-badge-11", label: "With Link" },
          { key: "v-badge-12", label: "With Count" },
        ],
      },
      {
        href: "/ui/feedback/kbd",
        name: "Kbd",
        variants: [
          { key: "v-kbd-1", label: "Default" },
          { key: "v-kbd-2", label: "Input Group" },
          { key: "v-kbd-3", label: "Grouped Keys" },
          { key: "v-kbd-4", label: "With Icons" },
          { key: "v-kbd-5", label: "In Tooltip" },
          { key: "v-kbd-6", label: "Reference List" },
          { key: "v-kbd-7", label: "Variant 7" },
          { key: "v-kbd-8", label: "Variant 8" },
          { key: "v-kbd-9", label: "Variant 9" },
          { key: "v-kbd-10", label: "Variant 10" },
        ],
      },
      {
        href: "/ui/feedback/progress",
        name: "Progress",
        variants: [
          { key: "v-progress-1", label: "Default" },
          { key: "v-progress-2", label: "With Formatted Value" },
          { key: "v-progress-3", label: "With Status Messages" },
          { key: "v-progress-4", label: "With Slider" },
          { key: "v-progress-5", label: "Multi-step" },
          { key: "v-progress-6", label: "Custom Colors" },
          { key: "v-progress-7", label: "Skills Meter" },
          { key: "v-progress-8", label: "File Upload Queue" },
          { key: "v-progress-9", label: "Budget Breakdown" },
          { key: "v-progress-10", label: "API Usage Tiers" },
        ],
      },
      {
        href: "/ui/feedback/skeleton",
        name: "Skeleton",
        variants: [
          { key: "v-skeleton-1", label: "Default" },
          { key: "v-skeleton-2", label: "Skeleton Only" },
          { key: "v-skeleton-3", label: "Card" },
          { key: "v-skeleton-4", label: "Dashboard Stats" },
          { key: "v-skeleton-5", label: "List with Actions" },
          { key: "v-skeleton-6", label: "Blog Article" },
          { key: "v-skeleton-7", label: "Data Table" },
          { key: "v-skeleton-8", label: "Sidebar Dashboard" },
          { key: "v-skeleton-9", label: "Chat Thread" },
          { key: "v-skeleton-10", label: "Settings Page" },
        ],
      },
      {
        href: "/ui/feedback/spinner",
        name: "Spinner",
        variants: [
          { key: "v-spinner-1", label: "Default" },
          { key: "v-spinner-2", label: "Input Group" },
          { key: "v-spinner-3", label: "In Buttons" },
          { key: "v-spinner-4", label: "In Empty State" },
          { key: "v-spinner-5", label: "Overlay" },
          { key: "v-spinner-6", label: "Full Page" },
          { key: "v-spinner-7", label: "Inline Loading" },
          { key: "v-spinner-8", label: "Overlay on Card" },
          { key: "v-spinner-9", label: "Color Variants" },
          { key: "v-spinner-10", label: "Variant 10" },
        ],
      },
      {
        href: "/ui/feedback/toast",
        name: "Toast",
        variants: [
          { key: "v-toast-1", label: "Default" },
          { key: "v-toast-2", label: "With Status" },
          { key: "v-toast-3", label: "Loading" },
          { key: "v-toast-4", label: "With Action" },
          { key: "v-toast-5", label: "Promise" },
          { key: "v-toast-6", label: "Varying Heights" },
          { key: "v-toast-7", label: "Submit with Error" },
          { key: "v-toast-8", label: "Staggered Burst" },
          { key: "v-toast-9", label: "Timeout Control" },
          { key: "v-toast-10", label: "Deploy Pipeline" },
        ],
      },
    ],
    label: "Feedback",
  },
  {
    components: [
      {
        href: "/ui/forms/checkbox",
        name: "Checkbox",
        variants: [
          { key: "v-checkbox-1", label: "Default" },
          { key: "v-checkbox-2", label: "Disabled" },
          { key: "v-checkbox-3", label: "With Description" },
          { key: "v-checkbox-4", label: "Card Style" },
          { key: "v-checkbox-5", label: "Form Integration" },
          { key: "v-checkbox-6", label: "Payment Card" },
          { key: "v-checkbox-7", label: "Select All" },
          { key: "v-checkbox-8", label: "Label Picker" },
          { key: "v-checkbox-9", label: "Notification Channels" },
          { key: "v-checkbox-10", label: "Multi-Consent" },
        ],
      },
      {
        href: "/ui/forms/checkbox-group",
        name: "Checkbox Group",
        variants: [
          { key: "v-checkbox-group-1", label: "Default" },
          { key: "v-checkbox-group-2", label: "With Disabled Item" },
          { key: "v-checkbox-group-3", label: "Parent Checkbox" },
          { key: "v-checkbox-group-4", label: "Nested Parent" },
          { key: "v-checkbox-group-5", label: "Form Integration" },
          { key: "v-checkbox-group-6", label: "Variant 6" },
          { key: "v-checkbox-group-7", label: "Variant 7" },
          { key: "v-checkbox-group-8", label: "Variant 8" },
          { key: "v-checkbox-group-9", label: "Variant 9" },
          { key: "v-checkbox-group-10", label: "Variant 10" },
        ],
      },
      {
        href: "/ui/forms/field",
        name: "Field",
        variants: [
          { key: "v-field-1", label: "Default" },
          { key: "v-field-2", label: "Variant 2" },
          { key: "v-field-3", label: "Variant 3" },
          { key: "v-field-4", label: "Variant 4" },
          { key: "v-field-5", label: "Variant 5" },
          { key: "v-field-6", label: "Variant 6" },
          { key: "v-field-7", label: "Variant 7" },
          { key: "v-field-8", label: "Variant 8" },
          { key: "v-field-9", label: "Variant 9" },
          { key: "v-field-10", label: "Variant 10" },
          { key: "v-field-11", label: "Variant 11" },
          { key: "v-field-12", label: "Variant 12" },
          { key: "v-field-13", label: "Variant 13" },
          { key: "v-field-14", label: "Variant 14" },
          { key: "v-field-15", label: "Variant 15" },
          { key: "v-field-16", label: "Variant 16" },
          { key: "v-field-17", label: "Variant 17" },
          { key: "v-field-18", label: "Variant 18" },
          { key: "v-field-19", label: "Variant 19" },
          { key: "v-field-20", label: "Variant 20" },
        ],
      },
      {
        href: "/ui/forms/fieldset",
        name: "Fieldset",
        variants: [
          { key: "v-fieldset-1", label: "Default" },
          { key: "v-fieldset-2", label: "Variant 2" },
          { key: "v-fieldset-3", label: "Variant 3" },
          { key: "v-fieldset-4", label: "Variant 4" },
          { key: "v-fieldset-5", label: "Variant 5" },
          { key: "v-fieldset-6", label: "Variant 6" },
          { key: "v-fieldset-7", label: "Variant 7" },
          { key: "v-fieldset-8", label: "Variant 8" },
          { key: "v-fieldset-9", label: "Variant 9" },
          { key: "v-fieldset-10", label: "Variant 10" },
        ],
      },
      {
        href: "/ui/forms/form",
        name: "Form",
        variants: [
          { key: "v-form-1", label: "Default" },
          { key: "v-form-2", label: "With Zod" },
          { key: "v-form-3", label: "Sign In" },
          { key: "v-form-4", label: "Profile Settings" },
          { key: "v-form-5", label: "Contact Form" },
          { key: "v-form-6", label: "Change Password" },
          { key: "v-form-7", label: "Newsletter Signup" },
          { key: "v-form-8", label: "Multi-step Onboarding" },
          { key: "v-form-9", label: "Variant 9" },
          { key: "v-form-10", label: "Variant 10" },
        ],
      },
      {
        href: "/ui/forms/input",
        name: "Input",
        variants: [
          { key: "v-input-1", label: "Default" },
          { key: "v-input-2", label: "With Label" },
          { key: "v-input-3", label: "With Description" },
          { key: "v-input-4", label: "With Error Message" },
          { key: "v-input-5", label: "With Character Counter" },
          { key: "v-input-6", label: "Password" },
          { key: "v-input-7", label: "Phone" },
          { key: "v-input-8", label: "URL" },
          { key: "v-input-9", label: "Number" },
          { key: "v-input-10", label: "Date" },
          { key: "v-input-11", label: "File Upload" },
          { key: "v-input-12", label: "With Required Indicator" },
          { key: "v-input-13", label: "Time" },
          { key: "v-input-14", label: "Multiple Fields" },
          { key: "v-input-15", label: "Label with Tooltip" },
          { key: "v-input-16", label: "With Badge" },
          { key: "v-input-17", label: "With Optional Badge" },
          { key: "v-input-18", label: "Link & Visibility Toggle" },
          { key: "v-input-19", label: "Multiple Errors" },
          { key: "v-input-20", label: "Password Strength" },
        ],
      },
      {
        href: "/ui/forms/input-group",
        name: "Input Group",
        variants: [
          { key: "v-input-group-1", label: "Default" },
          { key: "v-input-group-2", label: "With End Icon" },
          { key: "v-input-group-3", label: "With Start Text" },
          { key: "v-input-group-4", label: "With End Text" },
          { key: "v-input-group-5", label: "With Start & End Text" },
          { key: "v-input-group-6", label: "With Tooltip" },
          { key: "v-input-group-7", label: "With Icon Button" },
          { key: "v-input-group-8", label: "With Button" },
          { key: "v-input-group-9", label: "With Badge" },
          { key: "v-input-group-10", label: "With Keyboard Shortcut" },
          { key: "v-input-group-11", label: "With Inner Label" },
          { key: "v-input-group-12", label: "Sizes" },
          { key: "v-input-group-13", label: "Disabled" },
          { key: "v-input-group-14", label: "Loading" },
          { key: "v-input-group-15", label: "With Number Field" },
          { key: "v-input-group-16", label: "With Textarea" },
          { key: "v-input-group-17", label: "Variant 17" },
          { key: "v-input-group-18", label: "Variant 18" },
          { key: "v-input-group-19", label: "Variant 19" },
          { key: "v-input-group-20", label: "Variant 20" },
        ],
      },
      {
        href: "/ui/forms/label",
        name: "Label",
        variants: [
          { key: "v-label-1", label: "Default" },
          { key: "v-label-2", label: "With Checkbox" },
          { key: "v-label-3", label: "With Textarea" },
          { key: "v-label-4", label: "With Required Indicator" },
          { key: "v-label-5", label: "With Optional Indicator" },
          { key: "v-label-6", label: "With Tooltip Icon" },
          { key: "v-label-7", label: "With Badge Indicator" },
          { key: "v-label-8", label: "With Character Counter" },
          { key: "v-label-9", label: "With Helper Text" },
          { key: "v-label-10", label: "With Status Dot" },
        ],
      },
      {
        href: "/ui/forms/meter",
        name: "Meter",
        variants: [
          { key: "v-meter-1", label: "Default" },
          { key: "v-meter-2", label: "With Label" },
          { key: "v-meter-3", label: "With Formatted Value" },
          { key: "v-meter-4", label: "With Range" },
          { key: "v-meter-5", label: "Variant 5" },
          { key: "v-meter-6", label: "Variant 6" },
          { key: "v-meter-7", label: "Variant 7" },
          { key: "v-meter-8", label: "Variant 8" },
          { key: "v-meter-9", label: "Variant 9" },
          { key: "v-meter-10", label: "Variant 10" },
        ],
      },
      {
        href: "/ui/forms/number-field",
        name: "Number Field",
        variants: [
          { key: "v-number-field-1", label: "Default" },
          { key: "v-number-field-2", label: "Sizes" },
          { key: "v-number-field-3", label: "Disabled" },
          { key: "v-number-field-4", label: "With External Label" },
          { key: "v-number-field-5", label: "With Scrub" },
          { key: "v-number-field-6", label: "With Range" },
          { key: "v-number-field-7", label: "Formatted Value" },
          { key: "v-number-field-8", label: "With Step" },
          { key: "v-number-field-9", label: "Form Integration" },
          { key: "v-number-field-10", label: "Variant 10" },
        ],
      },
      {
        href: "/ui/forms/otp-field",
        name: "OTP Field",
        variants: [
          { key: "v-otp-field-1", label: "Default" },
          { key: "v-otp-field-2", label: "Large" },
          { key: "v-otp-field-3", label: "With Separator" },
          { key: "v-otp-field-4", label: "With Label" },
          { key: "v-otp-field-5", label: "Custom Sanitization" },
          { key: "v-otp-field-6", label: "Auto Validation" },
          { key: "v-otp-field-7", label: "Alphanumeric" },
          { key: "v-otp-field-8", label: "Placeholder Hints" },
          { key: "v-otp-field-9", label: "Masked Entry" },
          { key: "v-otp-field-10", label: "Variant 10" },
        ],
      },
      {
        href: "/ui/forms/radio-group",
        name: "Radio Group",
        variants: [
          { key: "v-radio-group-1", label: "Default" },
          { key: "v-radio-group-2", label: "Disabled" },
          { key: "v-radio-group-3", label: "With Description" },
          { key: "v-radio-group-4", label: "Card Style" },
          { key: "v-radio-group-5", label: "Colored Variants" },
          { key: "v-radio-group-6", label: "With Legend" },
          { key: "v-radio-group-7", label: "In Card with Description" },
          { key: "v-radio-group-8", label: "In Card with Icons" },
          { key: "v-radio-group-9", label: "Form Integration" },
          { key: "v-radio-group-10", label: "Variant 10" },
        ],
      },
      {
        href: "/ui/forms/slider",
        name: "Slider",
        variants: [
          { key: "v-slider-1", label: "Default" },
          { key: "v-slider-2", label: "With Label and Value" },
          { key: "v-slider-3", label: "Disabled" },
          { key: "v-slider-4", label: "With Reference Labels" },
          { key: "v-slider-5", label: "With Tick Marks" },
          { key: "v-slider-6", label: "Dynamic Tooltip" },
          { key: "v-slider-7", label: "Rating with Emoji" },
          { key: "v-slider-8", label: "Variant 8" },
          { key: "v-slider-9", label: "Variant 9" },
          { key: "v-slider-10", label: "Variant 10" },
        ],
      },
      {
        href: "/ui/forms/textarea",
        name: "Textarea",
        variants: [
          { key: "v-textarea-1", label: "Default" },
          { key: "v-textarea-2", label: "Sizes" },
          { key: "v-textarea-3", label: "Disabled" },
          { key: "v-textarea-4", label: "With Label" },
          { key: "v-textarea-5", label: "With Description" },
          { key: "v-textarea-6", label: "With Character Count" },
          { key: "v-textarea-7", label: "Form Integration" },
          { key: "v-textarea-8", label: "Variant 8" },
          { key: "v-textarea-9", label: "Variant 9" },
          { key: "v-textarea-10", label: "Variant 10" },
        ],
      },
    ],
    label: "Forms",
  },
  {
    components: [
      {
        href: "/ui/media/avatar",
        name: "Avatar",
        variants: [
          { key: "v-avatar-1", label: "Default" },
          { key: "v-avatar-2", label: "With Fallback" },
          { key: "v-avatar-3", label: "Sizes" },
          { key: "v-avatar-4", label: "Radius" },
          { key: "v-avatar-5", label: "Group" },
          { key: "v-avatar-6", label: "Group with Count" },
          { key: "v-avatar-7", label: "With Details & Badge" },
          { key: "v-avatar-8", label: "Social Proof" },
          { key: "v-avatar-9", label: "Social Proof (Initials)" },
          { key: "v-avatar-10", label: "With Hover Effect" },
          { key: "v-avatar-11", label: "Hover with Tooltips" },
          { key: "v-avatar-12", label: "In Empty State" },
          { key: "v-avatar-13", label: "Loading State" },
          { key: "v-avatar-14", label: "With Custom Badge" },
          { key: "v-avatar-15", label: "With Ring Animation" },
          { key: "v-avatar-16", label: "With Dropdown Menu" },
        ],
      },
      {
        href: "/ui/media/carousel",
        name: "Carousel",
        variants: [
          { key: "v-carousel-1", label: "Default" },
          { key: "v-carousel-2", label: "Multiple Items" },
          { key: "v-carousel-3", label: "Custom Spacing" },
          { key: "v-carousel-4", label: "Vertical Orientation" },
          { key: "v-carousel-5", label: "Autoplay" },
          { key: "v-carousel-6", label: "Testimonials" },
          { key: "v-carousel-7", label: "Product Showcase" },
          { key: "v-carousel-8", label: "Onboarding Steps" },
          { key: "v-carousel-9", label: "Team Members" },
          { key: "v-carousel-10", label: "With Thumbnails" },
        ],
      },
    ],
    label: "Media",
  },
  {
    components: [
      {
        href: "/ui/navigation/breadcrumb",
        name: "Breadcrumb",
        variants: [
          { key: "v-breadcrumb-1", label: "Default" },
          { key: "v-breadcrumb-2", label: "Custom Separator" },
          { key: "v-breadcrumb-3", label: "With Dropdown" },
          { key: "v-breadcrumb-4", label: "With Next.js Link" },
          { key: "v-breadcrumb-5", label: "With Icons" },
          { key: "v-breadcrumb-6", label: "With Avatar" },
          { key: "v-breadcrumb-7", label: "Inside Card" },
          { key: "v-breadcrumb-8", label: "With Home Icon" },
          { key: "v-breadcrumb-9", label: "Button-style" },
          { key: "v-breadcrumb-10", label: "Project Info" },
        ],
      },
      {
        href: "/ui/navigation/command",
        name: "Command",
        variants: [
          { key: "v-command-1", label: "Default" },
          { key: "v-command-2", label: "Simple Command" },
          { key: "v-command-3", label: "With Groups" },
          { key: "v-command-4", label: "File Search" },
          { key: "v-command-5", label: "User Search" },
          { key: "v-command-6", label: "Action Palette" },
          { key: "v-command-7", label: "Recent & Favorites" },
          { key: "v-command-8", label: "Variant 8" },
          { key: "v-command-9", label: "Variant 9" },
          { key: "v-command-10", label: "Variant 10" },
        ],
      },
      {
        href: "/ui/navigation/menu",
        name: "Menu",
        variants: [
          { key: "v-menu-1", label: "Default" },
          { key: "v-menu-2", label: "Open on Hover" },
          { key: "v-menu-3", label: "With Checkbox" },
          { key: "v-menu-4", label: "With Switch" },
          { key: "v-menu-5", label: "With Radio Group" },
          { key: "v-menu-6", label: "With Link" },
          { key: "v-menu-7", label: "With Group Label" },
          { key: "v-menu-8", label: "Nested Menu" },
          { key: "v-menu-9", label: "Close on Click" },
          { key: "v-menu-10", label: "Open a Dialog" },
        ],
      },
      {
        href: "/ui/navigation/pagination",
        name: "Pagination",
        variants: [
          { key: "v-pagination-1", label: "Default" },
          { key: "v-pagination-2", label: "Without Labels" },
          { key: "v-pagination-3", label: "With Hover Effect" },
          { key: "v-pagination-4", label: "Circle Buttons" },
          { key: "v-pagination-5", label: "Go-To-Page Input" },
          { key: "v-pagination-6", label: "In Card" },
          { key: "v-pagination-7", label: "With Arrows" },
          { key: "v-pagination-8", label: "Page Info Center" },
          { key: "v-pagination-9", label: "Page Info Left" },
          { key: "v-pagination-10", label: "Outline Style" },
          { key: "v-pagination-11", label: "Page Select & First/Last" },
          { key: "v-pagination-12", label: "Numbered with Go-To" },
          { key: "v-pagination-13", label: "Full Featured" },
          { key: "v-pagination-14", label: "Variant 14" },
          { key: "v-pagination-15", label: "Variant 15" },
        ],
      },
      {
        href: "/ui/navigation/tabs",
        name: "Tabs",
        variants: [
          { key: "v-tabs-1", label: "Default" },
          { key: "v-tabs-2", label: "Underline Variant" },
          { key: "v-tabs-3", label: "Vertical" },
          { key: "v-tabs-4", label: "Underline Vertical" },
          { key: "v-tabs-5", label: "With Card & Input" },
          { key: "v-tabs-6", label: "Underline Style" },
          { key: "v-tabs-7", label: "Vertical Orientation" },
          { key: "v-tabs-8", label: "Underline & Vertical" },
          { key: "v-tabs-9", label: "With Icons" },
          { key: "v-tabs-10", label: "With Badge Counts" },
          { key: "v-tabs-11", label: "Icons & Line Variant" },
          { key: "v-tabs-12", label: "Segmented Control" },
          { key: "v-tabs-13", label: "Variant 13" },
          { key: "v-tabs-14", label: "Variant 14" },
          { key: "v-tabs-15", label: "Variant 15" },
        ],
      },
    ],
    label: "Navigation",
  },
  {
    components: [
      {
        href: "/ui/overlays/alert-dialog",
        name: "Alert Dialog",
        variants: [
          { key: "v-alert-dialog-1", label: "Default" },
          { key: "v-alert-dialog-2", label: "Small Size" },
          { key: "v-alert-dialog-3", label: "Within a Dialog" },
          { key: "v-alert-dialog-4", label: "Task Success" },
          { key: "v-alert-dialog-5", label: "Account Deactivation" },
          { key: "v-alert-dialog-6", label: "Unsaved Changes" },
          { key: "v-alert-dialog-7", label: "e-ticket Registration" },
          { key: "v-alert-dialog-8", label: "System Update" },
          { key: "v-alert-dialog-9", label: "Expired Subscription" },
          { key: "v-alert-dialog-10", label: "Logout Confirmation" },
        ],
      },
      {
        href: "/ui/overlays/context-menu",
        name: "Context Menu",
        variants: [
          { key: "v-context-menu-1", label: "Default" },
          { key: "v-context-menu-2", label: "Variant 2" },
          { key: "v-context-menu-3", label: "Variant 3" },
          { key: "v-context-menu-4", label: "Variant 4" },
          { key: "v-context-menu-5", label: "Variant 5" },
          { key: "v-context-menu-6", label: "Variant 6" },
          { key: "v-context-menu-7", label: "Variant 7" },
          { key: "v-context-menu-8", label: "Variant 8" },
          { key: "v-context-menu-9", label: "Variant 9" },
          { key: "v-context-menu-10", label: "Variant 10" },
        ],
      },
      {
        href: "/ui/overlays/dialog",
        name: "Dialog",
        variants: [
          { key: "v-dialog-1", label: "Default" },
          { key: "v-dialog-2", label: "Open from Menu" },
          { key: "v-dialog-3", label: "Bare Footer" },
          { key: "v-dialog-4", label: "Scroll Inside" },
          { key: "v-dialog-5", label: "Nested Dialogs" },
          { key: "v-dialog-6", label: "Destructive Action" },
          { key: "v-dialog-7", label: "Cookie Preferences" },
          { key: "v-dialog-8", label: "Session Expired" },
          { key: "v-dialog-9", label: "Edit Profile" },
          { key: "v-dialog-10", label: "Invite Team Members" },
        ],
      },
      {
        href: "/ui/overlays/drawer",
        name: "Drawer",
        variants: [
          { key: "v-drawer-1", label: "Default" },
          { key: "v-drawer-2", label: "Multiple Positions (Inset)" },
          { key: "v-drawer-3", label: "Multiple Positions (Straight)" },
          { key: "v-drawer-4", label: "Nested Drawers" },
          { key: "v-drawer-5", label: "Navigation Menu" },
          { key: "v-drawer-6", label: "Filter & Sort Panel" },
          { key: "v-drawer-7", label: "Shopping Cart" },
          { key: "v-drawer-8", label: "Notification Center" },
          { key: "v-drawer-9", label: "Variant 9" },
          { key: "v-drawer-10", label: "Variant 10" },
        ],
      },
      {
        href: "/ui/overlays/popover",
        name: "Popover",
        variants: [
          { key: "v-popover-1", label: "Default" },
          { key: "v-popover-2", label: "With Close Button" },
          { key: "v-popover-3", label: "Tooltip Style" },
          { key: "v-popover-4", label: "Animated" },
          { key: "v-popover-5", label: "Multiple Triggers" },
          { key: "v-popover-6", label: "Placement" },
          { key: "v-popover-7", label: "User Profile Card" },
          { key: "v-popover-8", label: "Timestamp Detail" },
          { key: "v-popover-9", label: "Quick Settings" },
          { key: "v-popover-10", label: "Feature Tour" },
          { key: "v-popover-11", label: "Share Link" },
          { key: "v-popover-12", label: "Accent Color Picker" },
          { key: "v-popover-13", label: "Keyboard Shortcuts" },
          { key: "v-popover-14", label: "Filter Panel" },
          { key: "v-popover-15", label: "Set a Reminder" },
        ],
      },
      {
        href: "/ui/overlays/sheet",
        name: "Sheet",
        variants: [
          { key: "v-sheet-1", label: "Default" },
          { key: "v-sheet-2", label: "With Inset" },
          { key: "v-sheet-3", label: "Side Sheets" },
          { key: "v-sheet-4", label: "Scrollable Content" },
          { key: "v-sheet-5", label: "Shopping Cart" },
          { key: "v-sheet-6", label: "Notification Center" },
          { key: "v-sheet-7", label: "Team Invite" },
          { key: "v-sheet-8", label: "Activity Log" },
          { key: "v-sheet-9", label: "Navigation Menu" },
          { key: "v-sheet-10", label: "Issue Detail" },
        ],
      },
      {
        href: "/ui/overlays/tooltip",
        name: "Tooltip",
        variants: [
          { key: "v-tooltip-1", label: "Default" },
          { key: "v-tooltip-2", label: "Grouped Tooltips" },
          { key: "v-tooltip-3", label: "Animated" },
          { key: "v-tooltip-4", label: "Placement" },
          { key: "v-tooltip-5", label: "Info Icon" },
          { key: "v-tooltip-6", label: "Rich Tooltip" },
          { key: "v-tooltip-7", label: "Keyboard Shortcut Toolbar" },
          { key: "v-tooltip-8", label: "Avatar Stack" },
          { key: "v-tooltip-9", label: "Trend Metrics" },
          { key: "v-tooltip-10", label: "Color Palette" },
          { key: "v-tooltip-11", label: "Copy to Clipboard" },
          { key: "v-tooltip-12", label: "Feature Gate" },
        ],
      },
    ],
    label: "Overlays",
  },
  {
    components: [
      {
        href: "/ui/pickers/autocomplete",
        name: "Autocomplete",
        variants: [
          { key: "v-autocomplete-1", label: "Default" },
          { key: "v-autocomplete-2", label: "Sizes" },
          { key: "v-autocomplete-3", label: "With Label" },
          { key: "v-autocomplete-4", label: "Inline" },
          { key: "v-autocomplete-5", label: "Auto Highlight" },
          { key: "v-autocomplete-6", label: "With Trigger & Clear" },
          { key: "v-autocomplete-7", label: "With Clear Button" },
          { key: "v-autocomplete-8", label: "With Search Icon" },
          { key: "v-autocomplete-9", label: "Grouped Items" },
          { key: "v-autocomplete-10", label: "Limit Results" },
          { key: "v-autocomplete-11", label: "Async Search" },
          { key: "v-autocomplete-12", label: "Form Integration" },
          { key: "v-autocomplete-13", label: "Timezone Picker" },
          { key: "v-autocomplete-14", label: "Person Picker" },
          { key: "v-autocomplete-15", label: "Variant 15" },
        ],
      },
      {
        href: "/ui/pickers/calendar",
        name: "Calendar",
        variants: [
          { key: "v-calendar-1", label: "Default" },
          { key: "v-calendar-2", label: "Fallback Only" },
          { key: "v-calendar-3", label: "Sizes" },
          { key: "v-calendar-4", label: "Dropdown Navigation" },
          { key: "v-calendar-5", label: "Select Dropdown" },
          { key: "v-calendar-6", label: "Combobox Dropdown" },
          { key: "v-calendar-7", label: "Multiple Selection" },
          { key: "v-calendar-8", label: "Appointment Booking" },
          { key: "v-calendar-9", label: "Two-Month Range" },
          { key: "v-calendar-10", label: "Event Indicators" },
          { key: "v-calendar-11", label: "With Presets" },
          { key: "v-calendar-12", label: "Date of Birth" },
          { key: "v-calendar-13", label: "Week Picker" },
          { key: "v-calendar-14", label: "Variant 14" },
          { key: "v-calendar-15", label: "Variant 15" },
        ],
      },
      {
        href: "/ui/pickers/combobox",
        name: "Combobox",
        variants: [
          { key: "v-combobox-1", label: "Default" },
          { key: "v-combobox-2", label: "Disabled" },
          { key: "v-combobox-3", label: "Sizes" },
          { key: "v-combobox-4", label: "With Label" },
          { key: "v-combobox-5", label: "Auto Highlight" },
          { key: "v-combobox-6", label: "With Clear Button" },
          { key: "v-combobox-7", label: "With Groups" },
          { key: "v-combobox-8", label: "Multiple Selection" },
          { key: "v-combobox-9", label: "With Search Icon" },
          { key: "v-combobox-10", label: "With Trigger Button" },
          { key: "v-combobox-11", label: "With Select Button" },
          { key: "v-combobox-12", label: "Form Integration" },
          { key: "v-combobox-13", label: "Form Integration (Multi)" },
          { key: "v-combobox-14", label: "Async Search" },
          { key: "v-combobox-15", label: "Rich Item Rendering" },
          { key: "v-combobox-16", label: "Controlled" },
          { key: "v-combobox-17", label: "Variant 17" },
        ],
      },
      {
        href: "/ui/pickers/date-picker",
        name: "Date Picker",
        variants: [
          { key: "v-date-picker-1", label: "Default" },
          { key: "v-date-picker-2", label: "Date Range" },
          { key: "v-date-picker-3", label: "Dropdown Navigation" },
          { key: "v-date-picker-4", label: "With Presets" },
          { key: "v-date-picker-5", label: "With Input" },
          { key: "v-date-picker-6", label: "Auto-close on Select" },
          { key: "v-date-picker-7", label: "Appointment Booking" },
          { key: "v-date-picker-8", label: "Meeting Scheduler" },
          { key: "v-date-picker-9", label: "Delivery Date" },
          { key: "v-date-picker-10", label: "Task Deadline" },
        ],
      },
      {
        href: "/ui/pickers/select",
        name: "Select",
        variants: [
          { key: "v-select-1", label: "Default" },
          { key: "v-select-2", label: "Variant 2" },
          { key: "v-select-3", label: "Variant 3" },
          { key: "v-select-4", label: "Variant 4" },
          { key: "v-select-5", label: "Variant 5" },
          { key: "v-select-6", label: "Variant 6" },
          { key: "v-select-7", label: "Variant 7" },
          { key: "v-select-8", label: "Variant 8" },
          { key: "v-select-9", label: "Variant 9" },
          { key: "v-select-10", label: "Variant 10" },
        ],
      },
    ],
    label: "Pickers",
  },
];

export const totalComponents = catalogue.reduce(
  (sum, cat) => sum + cat.components.length,
  0,
);
