/**
 * Registry Categories Type Definition
 *
 * This file defines all valid categories that can be used in registry items.
 * All categories are treated equally - no distinction between component and tag categories.
 */

// All registry categories in display order
export const registryCategories = [
  // UI components
  "accordion",
  "alert",
  "alert dialog",
  "autocomplete",
  "avatar",
  "badge",
  "breadcrumb",
  "button",
  "calendar",
  "card",
  "carousel",
  "chart",
  "checkbox",
  "checkbox group",
  "collapsible",
  "combobox",
  "command",
  "context menu",
  "date picker",
  "dialog",
  "drawer",
  "dropdown",
  "empty state",
  "field",
  "fieldset",
  "form",
  "frame",
  "group",
  "input",
  "input group",
  "input otp",
  "kbd",
  "label",
  "menu",
  "meter",
  "number field",
  "pagination",
  "popover",
  "preview card",
  "progress",
  "radio group",
  "scroll area",
  "select",
  "separator",
  "sheet",
  "skeleton",
  "slider",
  "spinner",
  "switch",
  "table",
  "tabs",
  "textarea",
  "toast",
  "toggle",
  "toggle group",
  "toolbar",
  "tooltip",
  // Motion component categories
  "text animation",
  "scroll animation",
  "hover animation",
  // Text animation components
  "text reveal",
  "text scramble",
  "scramble hover",
  "typewriter",
  "text loop",
  "text morph",
  "text roll",
  "flip words",
  "counting number",
  "text rotate",
  "vertical cut reveal",
  "letter swap hover",
  "text shimmer",
  "text shimmer wave",
  "text gradient",
  "text highlight",
  "sliding number",
  "animated number",
  "spinning text",
  "breathing text",
  "splitting text",
  "rolling text",
  "rotating text",
  "morphing text",
  "colorful text",
  "encrypted text",
  "text generate effect",
  "letter 3d swap",
  "random letter swap",
  "scroll swap text",
  "variable font hover",
  "variable font cursor proximity",
  "text cursor proximity",
  "text along path",
  // Scroll animation components
  "scroll reveal",
  "scroll progress",
  "scroll velocity text",
  "parallax floating",
  "stacking cards",
  "progressive blur",
  "layout animation",
  "marquee animation",
  "background animation",
  "navigation animation",
  "carousel animation",
  "physics animation",
  "image animation",
  "svg animation",
  "filter effect",
  "button animation",
  "block animation",
  // Features and states
  "async",
  "copy",
  "disabled",
  "error",
  "file",
  "filter",
  "info",
  "loading",
  "multiselect",
  "password",
  "search",
  "sort",
  "success",
  "tag",
  "tanstack",
  "text editor",
  "time",
  "timezone",
  "upload",
  "validation",
  "warning",
  "zod",
] as const;

export type RegistryCategory = (typeof registryCategories)[number];

// Helper function to get category sort order
export function getCategorySortOrder(category: string): number {
  const index = registryCategories.indexOf(category as RegistryCategory);
  return index === -1 ? Number.POSITIVE_INFINITY : index;
}

// Helper function to validate if a string is a valid RegistryCategory
export function isValidRegistryCategory(
  category: string,
): category is RegistryCategory {
  return registryCategories.includes(category as RegistryCategory);
}
