#!/usr/bin/env tsx
/**
 * Usage:
 *   bun run variants:create <name1> [name2 ...] [--count=N] [--force] [--placeholder-only] [--reset]
 *
 * Examples:
 *   bun run variants:create button                                   → 10 variants + registry entry
 *   bun run variants:create switch toggle-group toggle toolbar        → 10 variants each
 *   bun run variants:create button --count=5                         → 5 variants
 *   bun run variants:create button --force                           → overwrite ALL existing files
 *   bun run variants:create button --placeholder-only                → overwrite only placeholder files
 *   bun run variants:create button --reset                           → revert generated files to placeholder
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const VARIANTS_DIR = join(__dirname, "../registry/default/variants");
const REGISTRY_FILE = join(__dirname, "../registry/registry-variants.ts");
const DEFAULT_COUNT = 10;

// Matches files that only contain the generic placeholder (no real imports or logic)
const PLACEHOLDER_RE =
  /^export default function Component\(\)\s*\{\s*return\s*<div>Component<\/div>;\s*\}[\s]*$/;

// Matches files generated by this script: single import + simple self-closing JSX return
const GENERATED_RE =
  /^import \{[^}]+\} from "@\/registry\/default\/ui\/[^"]+";[\s\n]+export default function Component\(\)\s*\{\s*return\s*<\w[\w.]*\s*\/>;\s*\}[\s]*$/;

const PLACEHOLDER_CONTENT = `export default function Component() {
  return <div>Component</div>;
}
`;

// ---------------------------------------------------------------------------
// TSX file helpers
// ---------------------------------------------------------------------------

function template(name: string): string {
  const pascal = name
    .split("-")
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");

  return `import { ${pascal} } from "@/registry/default/ui/${name}";

export default function Component() {
  return <${pascal} />;
}
`;
}

function readSafe(filepath: string): string {
  try {
    return readFileSync(filepath, "utf-8");
  } catch {
    return "";
  }
}

function isPlaceholder(filepath: string): boolean {
  return PLACEHOLDER_RE.test(readSafe(filepath));
}

function isGenerated(filepath: string): boolean {
  return GENERATED_RE.test(readSafe(filepath));
}

function createVariantFiles(
  name: string,
  count: number,
  force: boolean,
  placeholderOnly: boolean,
  reset: boolean,
): void {
  const created: string[] = [];
  const updated: string[] = [];
  const skipped: string[] = [];

  for (let i = 1; i <= count; i++) {
    const filename = `v-${name}-${i}.tsx`;
    const filepath = join(VARIANTS_DIR, filename);

    if (existsSync(filepath)) {
      if (reset) {
        if (isGenerated(filepath)) {
          writeFileSync(filepath, PLACEHOLDER_CONTENT, "utf-8");
          updated.push(filename);
        } else {
          skipped.push(filename);
        }
      } else if (force || (placeholderOnly && isPlaceholder(filepath))) {
        writeFileSync(filepath, template(name), "utf-8");
        updated.push(filename);
      } else {
        skipped.push(filename);
      }
      continue;
    }

    writeFileSync(filepath, template(name), "utf-8");
    created.push(filename);
  }

  if (created.length > 0) {
    console.log(`[${name}] Created ${created.length} file(s):`);
    for (const f of created) console.log(`  + ${f}`);
  }

  if (updated.length > 0) {
    const verb = reset ? "Reset" : "Updated";
    console.log(`[${name}] ${verb} ${updated.length} file(s):`);
    for (const f of updated) console.log(`  ~ ${f}`);
  }

  if (skipped.length > 0) {
    console.log(
      `[${name}] Skipped ${skipped.length} file(s) (real content preserved):`,
    );
    for (const f of skipped) console.log(`  . ${f}`);
  }
}

// ---------------------------------------------------------------------------
// registry-variants.ts helpers
// ---------------------------------------------------------------------------

/**
 * Convert a kebab-case component name to the registry category string.
 * e.g. "alert-dialog" → "alert dialog", "toggle-group" → "toggle group"
 * Special cases that don't follow the simple pattern are mapped explicitly.
 */
const CATEGORY_OVERRIDES: Record<string, string> = {
  "context-menu": "menu",
  "date-picker": "date picker",
  empty: "empty state",
  "otp-field": "input otp",
};

function toCategory(name: string): string {
  return CATEGORY_OVERRIDES[name] ?? name.replace(/-/g, " ");
}

/** Build the Array.from block that will be inserted into registry-variants.ts */
function registryBlock(name: string, count: number): string {
  const category = toCategory(name);
  const dep = name; // e.g. "button", "toggle-group"

  return (
    `  // --- ${name} ---\n` +
    `  ...Array.from({ length: ${count} }, (_, i) =>\n` +
    `    createVariant({\n` +
    `      category: "${category}",\n` +
    `      dependencies: ["${dep}"],\n` +
    `      name: \`v-${name}-\${i + 1}\`,\n` +
    `    }),\n` +
    `  ),`
  );
}

function updateRegistry(name: string, count: number, force: boolean): void {
  if (!existsSync(REGISTRY_FILE)) {
    console.warn("  registry-variants.ts not found, skipping registry update.");
    return;
  }

  let src = readFileSync(REGISTRY_FILE, "utf-8");
  const marker = `// --- ${name} ---`;

  if (src.includes(marker)) {
    if (!force) {
      console.log(
        `  [registry] "${name}" already exists — use --force to update count`,
      );
      return;
    }
    // Find the Array.from({ length: N }) that immediately follows this marker
    // and replace just the number.
    const markerIndex = src.indexOf(marker);
    const afterMarker = src.slice(markerIndex);
    const updated = afterMarker.replace(
      /Array\.from\(\{ length: \d+/,
      `Array.from({ length: ${count}`,
    );
    if (updated === afterMarker) {
      console.warn(
        `  [registry] Could not update count for "${name}" (pattern mismatch)`,
      );
      return;
    }
    src = src.slice(0, markerIndex) + updated;
    console.log(`  [registry] Updated "${name}" count to ${count}`);
  } else {
    // Insert before the closing `];`
    const closeIndex = src.lastIndexOf("];");
    if (closeIndex === -1) {
      console.warn(
        "  [registry] Could not locate closing ]; in registry-variants.ts",
      );
      return;
    }
    const block = "\n" + registryBlock(name, count) + "\n";
    src = src.slice(0, closeIndex) + block + src.slice(closeIndex);
    console.log(`  [registry] Added "${name}" (${count} variants)`);
  }

  writeFileSync(REGISTRY_FILE, src, "utf-8");
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

function main(): void {
  const args = process.argv.slice(2);

  // Parse --count=N or --count N
  let count = DEFAULT_COUNT;
  const countFlagIndex = args.findIndex((a) => a.startsWith("--count"));
  if (countFlagIndex !== -1) {
    const flag = args[countFlagIndex];
    const value = flag.includes("=")
      ? flag.split("=")[1]
      : args[countFlagIndex + 1];
    const parsed = Number.parseInt(value ?? "", 10);
    if (Number.isNaN(parsed) || parsed < 1) {
      console.error("Invalid --count value. Must be a positive integer.");
      process.exit(1);
    }
    count = parsed;
    args.splice(countFlagIndex, flag.includes("=") ? 1 : 2);
  }

  const force = args.includes("--force");
  const placeholderOnly = args.includes("--placeholder-only");
  const reset = args.includes("--reset");
  const noRegistry = args.includes("--no-registry");

  const modeFlags = [force, placeholderOnly, reset].filter(Boolean).length;
  if (modeFlags > 1) {
    console.error("Cannot combine --force, --placeholder-only, and --reset.");
    process.exit(1);
  }

  const names = args.filter((a) => !a.startsWith("--"));

  if (names.length === 0) {
    console.error(
      "Usage: bun run variants:create <name1> [name2 ...] [--count=N] [--force] [--placeholder-only] [--reset]",
    );
    console.error(
      "Example: bun run variants:create switch toggle-group toggle toolbar",
    );
    process.exit(1);
  }

  for (const raw of names) {
    const name = raw.trim().toLowerCase();
    if (!/^[a-z][a-z0-9-]*$/.test(name)) {
      console.error(
        `Invalid name "${name}". Use lowercase letters, numbers, and hyphens only.`,
      );
      process.exit(1);
    }
  }

  if (!existsSync(VARIANTS_DIR)) {
    mkdirSync(VARIANTS_DIR, { recursive: true });
  }

  for (const raw of names) {
    const name = raw.trim().toLowerCase();
    createVariantFiles(name, count, force, placeholderOnly, reset);
    if (!reset && !noRegistry) {
      updateRegistry(name, count, force);
    }
  }
}

main();
